/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IZklabV1Callee,
  IZklabV1CalleeInterface,
} from "../../Factory.sol/IZklabV1Callee";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "ZklabV1Call",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZklabV1Callee__factory {
  static readonly abi = _abi;
  static createInterface(): IZklabV1CalleeInterface {
    return new utils.Interface(_abi) as IZklabV1CalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZklabV1Callee {
    return new Contract(address, _abi, signerOrProvider) as IZklabV1Callee;
  }
}
