/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IFactoryInterface extends utils.Interface {
  functions: {
    "getController()": FunctionFragment;
    "kacyToken()": FunctionFragment;
    "minimumKacy()": FunctionFragment;
    "newPool()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getController"
      | "kacyToken"
      | "minimumKacy"
      | "newPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getController",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kacyToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minimumKacy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "newPool", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kacyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minimumKacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newPool", data: BytesLike): Result;

  events: {};
}

export interface IFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getController(overrides?: CallOverrides): Promise<[string]>;

    kacyToken(overrides?: CallOverrides): Promise<[string]>;

    minimumKacy(overrides?: CallOverrides): Promise<[BigNumber]>;

    newPool(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getController(overrides?: CallOverrides): Promise<string>;

  kacyToken(overrides?: CallOverrides): Promise<string>;

  minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;

  newPool(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getController(overrides?: CallOverrides): Promise<string>;

    kacyToken(overrides?: CallOverrides): Promise<string>;

    minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;

    newPool(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getController(overrides?: CallOverrides): Promise<BigNumber>;

    kacyToken(overrides?: CallOverrides): Promise<BigNumber>;

    minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;

    newPool(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kacyToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minimumKacy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newPool(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
