/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IFactoryDefInterface extends utils.Interface {
  functions: {
    "kacyToken()": FunctionFragment;
    "minimumKacy()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "kacyToken" | "minimumKacy"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "kacyToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minimumKacy",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "kacyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minimumKacy",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFactoryDef extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFactoryDefInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    kacyToken(overrides?: CallOverrides): Promise<[string]>;

    minimumKacy(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  kacyToken(overrides?: CallOverrides): Promise<string>;

  minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    kacyToken(overrides?: CallOverrides): Promise<string>;

    minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    kacyToken(overrides?: CallOverrides): Promise<BigNumber>;

    minimumKacy(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    kacyToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minimumKacy(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
